# TURAN Dressing Table Video Generator - Enhanced Configuration
# Обновленная конфигурация с кинематографическими улучшениями

# Google Cloud настройки
google_cloud:
  project_id: "turantt"
  project_number: "850567696273"
  location: "us-central1"
  account: "talllggat07777@gmail.com"
  
# Настройки хранилища
storage:
  bucket_name: "turan-videos"
  input_folder: "images/dressing_tables"
  output_folder: "output/dressing_table_enhanced"
  temp_folder: "temp"
  scenarios_file: "generated_showcase_scenarios.json"
  analytics_file: "turan_enhanced_performance_report.json"
  
# Настройки Veo API (только VEO 3.0)
veo_api:
  model: "veo-3.0-generate-001"  # Фиксированная модель
  max_concurrent_operations: 2   # Консервативно для качества
  operation_timeout: 600
  retry_attempts: 3
  
# Настройки видео по умолчанию
video_defaults:
  duration_seconds: 8            # Фиксированная длительность
  aspect_ratio: "16:9"
  resolution: "1080p"
  generate_audio: true           # Русская озвучка
  enhance_prompt: true
  compression_quality: "optimized"
  person_generation: "allow_adult"
  sample_count: 1

# НОВЫЕ КИНЕМАТОГРАФИЧЕСКИЕ НАСТРОЙКИ
enhanced_settings:
  enabled: true                  # Включить улучшенные промпты по умолчанию
  default_cinematic_style: "commercial"  # commercial, lifestyle, dramatic, intimate
  default_lighting_mood: "golden_hour"   # golden_hour, morning_soft, evening_warm, dramatic_contrast, natural_bright
  
  # Профессиональные камеры для каждого стиля
  camera_equipment:
    commercial:
      - "ARRI ALEXA 35 with 50mm Zeiss Master Prime lens"
      - "Sony FX9 with Sigma 24-70mm f/2.8 cine lens"
      - "RED KOMODO 6K with 35mm vintage glass"
      - "ARRI MINI LF with 75mm Master Macro lens"
    
    lifestyle:
      - "Sony A7S III, 85mm f/1.4 GM lens"
      - "Canon R5 with 50mm f/1.2 RF lens"
      - "Panasonic GH6, 25mm f/1.7 lens"
    
    dramatic:
      - "RED MONSTRO 8K with anamorphic 50mm lens"
      - "ARRI ALEXA LF with 65mm Master Prime"
      - "Blackmagic URSA 12K, 35mm cine lens"
  
  # Описания освещения для каждого настроения
  lighting_descriptions:
    golden_hour:
      - "Warm golden hour sunlight streaming through floor-to-ceiling windows, creating ethereal atmosphere with dancing light particles"
      - "Magic hour lighting with honey-colored rays filtering through sheer curtains"
      - "Late afternoon sun creating dramatic rim lighting and warm, inviting glow"
    
    morning_soft:
      - "Gentle morning sunlight diffused through translucent curtains, creating soft, even illumination"
      - "Fresh daybreak lighting with cool-warm balance"
      - "Peaceful morning ambiance with natural north-facing window light"
    
    evening_warm:
      - "Cozy evening atmosphere with warm LED practicals and soft lamplight"
      - "Romantic twilight setting with warm tungsten lighting"
      - "Evening sanctuary lighting with multiple warm sources"
    
    dramatic_contrast:
      - "High contrast studio lighting with deep shadows and bright highlights"
      - "Dramatic directional lighting from multiple sources"
      - "Cinematic lighting setup with strong key light and subtle fill"
    
    natural_bright:
      - "Bright natural daylight from multiple windows creating crisp, clean illumination"
      - "Fresh architectural lighting emphasizing clean lines"
      - "Balanced daylight with soft environmental fill"

# Конфигурации для социальных сетей с оптимальными стилями
social_media_configs:
  youtube_facebook:
    model: "veo-3.0-generate-001"
    duration_seconds: 8
    aspect_ratio: "16:9"
    resolution: "1080p"
    generate_audio: true
    cinematic_style: "commercial"
    lighting_mood: "golden_hour"
    
  instagram_tiktok:
    model: "veo-3.0-generate-001"
    duration_seconds: 8
    aspect_ratio: "9:16"
    resolution: "1080p"
    generate_audio: true
    cinematic_style: "lifestyle"
    lighting_mood: "morning_soft"

# Информация о продукте TURAN Lux
product_info:
  name: "Туалетный столик TURAN Lux"
  description: "Кинематографический показ стильного и функционального решения"
  
  features:
    - "Белая закаленная стеклянная столешница"
    - "4 ящика (2 встроенных + 2 съемных)"
    - "Зеркало с 3 режимами подсветки LED"
    - "Металлические ножки"
    - "Стул с мягкой обивкой в комплекте"
    - "Регулируемое расположение внешних ящиков"
    - "Надёжные и устойчивые материалы"
    
  preservation_requirements:
    - "Сохранить белую стеклянную поверхность"
    - "Сохранить конфигурацию 4 ящиков"
    - "Сохранить LED зеркало"
    - "Сохранить металлические ножки"
    - "Не изменять дизайн столика"
    
  target_audience:
    - "Женщины 18-45 лет"
    - "Любители красоты и ухода за собой"
    - "Ценители стильного интерьера"
    - "Активные пользователи социальных сетей"

# УЛУЧШЕННЫЕ НЕГАТИВНЫЕ ПРОМПТЫ
negative_prompts:
  enhanced: "changing the TURAN dressing table design, removing original furniture, altering glass surface, modifying drawer configuration, changing LED mirror, different furniture style, poor quality, blurry, distorted, unnatural colors, bad lighting, amateur cinematography, unprofessional setup, subtitles, text overlay, watermarks, low resolution, pixelated, grainy, overexposed, underexposed, harsh shadows, flat lighting"
  
  specific_furniture_protection:
    - "changing the white glass surface"
    - "altering the 4-drawer system"
    - "modifying LED mirror lighting"
    - "changing metallic leg design"
    - "different furniture color"
    - "removing original table"
  
  technical_quality:
    - "poor video quality"
    - "amateur lighting setup"
    - "unprofessional cinematography"
    - "bad camera work"
    - "low resolution output"
    - "pixelated footage"
    - "motion blur artifacts"

# Аудио дизайн компоненты
audio_design:
  commercial_style:
    - "gentle morning ambiance, soft fabric sounds, warm contemporary piano score building subtly"
    - "sophisticated commercial audio with premium material interaction sounds"
    - "refined background music with authentic furniture interaction acoustics"
  
  lifestyle_style:
    - "intimate room tone with delicate material interactions, minimalist ambient music"
    - "natural home environment sounds with warm, family-friendly background music"
    - "peaceful bedroom atmosphere, soft drawer sliding sounds"
  
  dramatic_style:
    - "minimal ambient sounds with building orchestral score"
    - "sophisticated audio landscape with contemporary orchestral arrangement"
    - "dramatic commercial audio design with refined material sounds"

# Цветовые палитры
color_palettes:
  commercial:
    - "warm whites, brushed metallics, soft golden accents"
    - "pristine whites, cool silver metallic highlights, gentle cream undertones"
    - "elegant white glass dominance, warm brass accents, soft beige environmental tones"
  
  lifestyle:
    - "natural daylight whites, warm family home atmosphere"
    - "soft morning whites, natural skin-flattering lighting"
    - "comfortable living tones, warm environmental palette"
  
  dramatic:
    - "luxury whites with dramatic shadows, premium metallic accents"
    - "high contrast commercial whites, sophisticated metallic tones"
    - "pristine commercial whites, dramatic shadows, metallic highlights"

# Движения камеры
camera_movements:
  establishing_to_detail:
    - "Camera begins with wide establishing shot, then executes slow dolly movement forward with subtle downward tilt"
    - "Elegant crane movement descending from high angle to intimate eye-level perspective"
  
  orbital_showcase:
    - "Smooth tracking shot starting from left side, gracefully orbiting around the dressing table"
    - "Sophisticated lateral tracking combined with slow zoom"
  
  intimate_approach:
    - "Gentle push-in movement from medium shot to close-up"
    - "Smooth flowing camera movement demonstrating integration into routines"

# JSON структура мемных сценариев (сохранены из оригинала)
meme_scenarios:
  morning_chaos:
    - id: "morning_panic_1"
      english_prompt: "Keep the dressing table exactly as shown in image. Add: Woman rushes to the dressing table at 6 AM, frantically opens drawers searching for lipstick, panicked expression, scattered makeup items on glass surface, dramatic morning lighting, 8-second quick comedy scene"
      russian_voiceover: "Когда до работы 5 минут, а помады нигде нет! Столик TURAN спасёт любое утро!"
      emotion: "panic"
      duration_focus: "quick_action"
      enhancement_style: "lifestyle"  # Какой стиль применить для улучшения
      
    - id: "tiktok_fail_1"
      english_prompt: "Dressing table stays as in image. Add: Woman attempts TikTok makeup tutorial, everything goes wrong, makeup explodes everywhere on glass surface, mirror reflects the disaster, comedic timing, 8-second fail compilation"
      russian_voiceover: "Повторяем макияж с ТикТока на столике TURAN. Ожидание VS реальность!"
      emotion: "embarrassed_laugh"
      duration_focus: "quick_fail"
      enhancement_style: "dramatic"

# A/B тестирование настройки
ab_testing:
  enabled: true
  comparison_metrics:
    - "visual_quality"
    - "cinematic_appeal"
    - "brand_perception"
    - "engagement_potential"
  
  test_scenarios:
    traditional_vs_enhanced:
      traditional:
        use_enhanced_prompts: false
        simple_description: true
      enhanced:
        use_enhanced_prompts: true
        cinematic_style: "commercial"
        lighting_mood: "golden_hour"

# Аналитика и мониторинг
analytics:
  track_performance: true
  export_reports: true
  log_prompt_effectiveness: true
  
  metrics:
    - "total_generated"
    - "enhanced_prompts_used"
    - "traditional_prompts_used"
    - "scenarios_used"
    - "enhancement_usage_percentage"
    - "most_used_scenarios"
  
  reporting:
    auto_export: true
    include_prompt_analysis: true
    track_cinematic_styles: true
    monitor_lighting_preferences: true

# Настройки логирования
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "turan_enhanced_generator.log"
  max_file_size: "10MB"
  backup_count: 5

# Настройки мониторинга
monitoring:
  enable_progress_bar: true
  save_intermediate_results: true
  create_thumbnails: true
  generate_reports: true
  save_scenario_info: true
  track_enhancement_usage: true  # Новое: отслеживание использования улучшений

# Настройки обработки изображений
image_processing:
  supported_formats: [".jpg", ".jpeg", ".png", ".webp"]
  max_file_size: "50MB"
  auto_resize: true
  target_resolution:
    width: 1920
    height: 1080
  quality_enhancement: true
  preserve_original: true  # Не менять столик на изображении

# Настройки производительности
performance:
  max_concurrent_requests: 2  # Консервативно для качества
  request_timeout: 30
  retry_delay: 5
  batch_size: 5
  cache_results: true
  
  # Новые настройки для улучшенных промптов
  enhanced_processing:
    prompt_validation: true
    length_optimization: true
    style_consistency_check: true

# Контент стратегия для кинематографических видео
content_strategy:
  focus: "cinematic_furniture_showcase"
  tone: "professional_premium"
  duration: "8_seconds_optimal"
  
  target_platforms:
    - "YouTube"
    - "Instagram_Stories"
    - "Instagram_Reels"
    - "TikTok"
    - "Facebook"
  
  cinematic_elements:
    - "professional_camera_specifications"
    - "detailed_lighting_descriptions"
    - "sophisticated_camera_movements"
    - "audio_design_integration"
    - "color_palette_definition"
    - "technical_cinematography_terms"
    
  engagement_hooks:
    - "Professional cinematography quality"
    - "Luxury brand presentation"
    - "Premium furniture showcase"
    - "Cinematic lighting effects"
    - "Smooth camera movements"
    - "Integrated audio design"

# Брендинг TURAN Lux с кинематографическим подходом
branding:
  brand_name: "TURAN"
  product_line: "Lux"
  key_message: "Кинематографическое качество для премиум мебели"
  
  brand_values:
    - "Профессиональное качество"
    - "Кинематографический стиль"
    - "Премиум презентация"
    - "Техническое совершенство"
    - "Визуальное превосходство"
  
  visual_identity:
    cinematic_approach: true
    professional_standards: true
    premium_presentation: true
    
    colors:
      primary: "White glass surface with cinematic lighting"
      accent: "LED warm lighting with professional color grading"
      background: "Elegant interior with sophisticated atmosphere"
    
    style:
      - "Commercial cinematography"
      - "Professional lighting design"
      - "Sophisticated camera work"
      - "Premium visual quality"
      - "Cinematic color grading"
      - "Preserve original furniture integrity"

# Экспорт и интеграция
export_settings:
  formats:
    - "MP4"
    - "MOV" 
  
  metadata:
    include_scenario_info: true
    include_cinematic_style: true
    include_lighting_mood: true
    include_enhancement_status: true
  
  naming_convention: "turan_{style}_{scenario_id}_{image_name}_{timestamp}"
  
  quality_presets:
    youtube: "1080p, commercial style, golden hour lighting"
    instagram: "1080p, lifestyle style, morning soft lighting"
    tiktok: "1080p, lifestyle style, dramatic contrast lighting"
    premium: "1080p, dramatic style, cinematic lighting"

# Интеграция с внешними системами
integrations:
  google_cloud_storage:
    auto_upload: true
    metadata_tagging: true
    
  analytics_platforms:
    google_analytics: false
    custom_tracking: true
  
  social_media_apis:
    instagram_business: false
    youtube_api: false
    tiktok_business: false

# Обучение и оптимизация
learning:
  prompt_optimization:
    enabled: true
    feedback_collection: true
    success_pattern_analysis: true
  
  style_refinement:
    track_preferred_styles: true
    optimize_lighting_choices: true
    refine_camera_movements: true
  
  performance_tuning:
    monitor_generation_times: true
    track_success_rates: true
    optimize_configurations: true